import { useEffect, useMemo, useState } from 'react'
import Sidebar from '../../components/Sidebar/Sidebar'
import NewTaskModal from '../../components/tasks/NewTaskModal'
import EditTaskModal from '../../components/tasks/EditTaskModal'
import { apiRequest } from '../../services/api'
import './Board.css'
const columns = [{ key: 'PENDING', label: 'PENDIENTE', color: 'orange' }, { key: 'IN_PROGRESS', label: 'EN PROCESO', color: 'blue' }, { key: 'COMPLETED', label: 'COMPLETADA', color: 'green' }]; const dateFormatter = new Intl.DateTimeFormat('es-CO', { day: 'numeric', month: 'short' })
export default function Board({ courseId = null }) {
  const [courses, setCourses] = useState([]); const [error, setError] = useState(''); const [showModal, setShowModal] = useState(false); const [editingTask, setEditingTask] = useState(null); const load = () => apiRequest('/courses?limit=100').then((response) => setCourses(response.data || [])).catch((requestError) => setError(requestError.message)); useEffect(() => { load() }, [])
  const selectedCourse = courses.find((course) => course.id === courseId); const visibleCourses = selectedCourse ? [selectedCourse] : courses; const tasks = useMemo(() => visibleCourses.flatMap((course) => (course.tasks || []).map((task) => ({ ...task, course }))), [visibleCourses]); const total = tasks.length; const title = selectedCourse ? selectedCourse.name.toUpperCase() : 'Tablero general'; const refresh = () => { setEditingTask(null); setShowModal(false); load() }
  return <main className="board-page"><Sidebar active={selectedCourse ? 'courses' : 'board'} /><section className="dashboard-content"><header className="topbar"><span>{new Intl.DateTimeFormat('es-CO', { weekday: 'long', day: 'numeric', month: 'long' }).format(new Date())}</span><div><button className="semester">Ingeniería · 3.er semestre</button><span className="profile">{(JSON.parse(localStorage.getItem('user') || '{}').name || 'E').charAt(0).toUpperCase()}</span></div></header><div className="board-inner">{selectedCourse && <a className="back-courses" href="#courses">← MIS CURSOS</a>}<div className="board-heading"><div><h1>{title}</h1><p>{selectedCourse ? `${total} tareas` : `${total} tareas en ${courses.length} cursos`}</p></div><button className="new-task" onClick={() => setShowModal(true)}>＋ Nueva tarea</button></div>{error && <div className="dashboard-error">{error}</div>}<div className="board-columns">{columns.map((column) => <section className="board-column" key={column.key}><header><span>{column.label}</span><b className={column.color}>{tasks.filter((task) => task.status === column.key).length}</b></header>{tasks.filter((task) => task.status === column.key).map((task) => <article className={`board-task ${task.status === 'COMPLETED' ? 'completed' : ''}`} key={task.id} onClick={() => setEditingTask(task)}><div className="board-task-meta"><span className={`task-dot ${task.course.color || column.color}`} />{task.course.name}<em className={`priority ${task.priority.toLowerCase()}`}>{priorityLabel(task.priority)}</em></div><h3>{task.title}</h3><p>{task.dueDate ? dateFormatter.format(new Date(task.dueDate)) : 'Sin fecha'}</p></article>)}</section>)}</div></div></section>{showModal && <NewTaskModal courses={visibleCourses} onClose={() => setShowModal(false)} onCreated={refresh} />}{editingTask && <EditTaskModal task={editingTask} courses={visibleCourses} onClose={() => setEditingTask(null)} onSaved={refresh} onDeleted={refresh} />}</main>
}
function priorityLabel(priority) { return ({ HIGH: 'Alta', MEDIUM: 'Media', LOW: 'Baja' })[priority] || priority }
