import { useEffect, useState } from 'react'
import { ArchiveRestore, Trash2 } from 'lucide-react'
import Sidebar from '../../components/Sidebar/Sidebar'
import ConfirmModal from '../../components/ui/ConfirmModal'
import { apiRequest } from '../../services/api'
import './Archived.css'

export default function Archived() {
  const [courses, setCourses] = useState([]); const [tasks, setTasks] = useState([]); const [error, setError] = useState(''); const [confirmation, setConfirmation] = useState(null)
  const load = () => Promise.all([apiRequest('/courses/archived'), apiRequest('/tasks/archived')]).then(([courseResponse, taskResponse]) => { setCourses(Array.isArray(courseResponse) ? courseResponse : courseResponse.data || []); setTasks(Array.isArray(taskResponse) ? taskResponse : taskResponse.data || []) }).catch((requestError) => setError(requestError.message))
  useEffect(() => { load() }, [])
  const ask = (title, message, url, method = 'PATCH', danger = false) => setConfirmation({ title, message, confirmLabel: danger ? 'Eliminar definitivamente' : 'Confirmar', danger, action: async () => { await apiRequest(url, { method }); load() } })
  const finishConfirmation = async () => { try { await confirmation.action(); setConfirmation(null) } catch (requestError) { setError(requestError.message); setConfirmation(null) } }
  return <main className="archived-page"><Sidebar active="archived" /><section className="dashboard-content"><header className="topbar"><span>Elementos archivados</span></header><div className="archived-inner"><h1>Archivados</h1><p className="archived-subtitle">Puedes restaurarlos o eliminarlos definitivamente.</p>{error && <div className="dashboard-error">No se pudieron cargar los archivados: {error}</div>}<section className="archived-section"><h2>Cursos <small>{courses.length}</small></h2><div className="archived-grid">{courses.map((course) => <article className="archived-card" key={course.id}><div><span className="archived-label">CURSO</span><h3>{course.name}</h3><p>{course.tasks?.length || 0} tareas guardadas</p></div><div className="archived-actions"><button onClick={() => ask('Restaurar curso', `“${course.name}” volverá a aparecer en Mis cursos.`, `/courses/${course.id}/restore`)}><ArchiveRestore size={16} /> Restaurar</button><button className="danger" onClick={() => ask('Eliminar para siempre', `Se borrará “${course.name}” junto con sus tareas.`, `/courses/${course.id}`, 'DELETE', true)}><Trash2 size={16} /> Eliminar</button></div></article>)}{!courses.length && <p className="archived-empty">No hay cursos archivados.</p>}</div></section><section className="archived-section"><h2>Tareas <small>{tasks.length}</small></h2><div className="archived-grid">{tasks.map((task) => <article className="archived-card" key={task.id}><div><span className="archived-label">{task.course?.name || 'TAREA'}</span><h3>{task.title}</h3><p>{task.dueDate ? new Intl.DateTimeFormat('es-CO', { dateStyle: 'medium' }).format(new Date(task.dueDate)) : 'Sin fecha'}</p></div><div className="archived-actions"><button onClick={() => ask('Restaurar tarea', `“${task.title}” volverá a tu tablero.`, `/tasks/${task.id}/restore`)}><ArchiveRestore size={16} /> Restaurar</button><button className="danger" onClick={() => ask('Eliminar para siempre', `Se borrará “${task.title}” definitivamente.`, `/tasks/${task.id}`, 'DELETE', true)}><Trash2 size={16} /> Eliminar</button></div></article>)}{!tasks.length && <p className="archived-empty">No hay tareas archivadas.</p>}</div></section></div></section>{confirmation && <ConfirmModal {...confirmation} onClose={() => setConfirmation(null)} onConfirm={finishConfirmation} />}</main>
}
