import { useState } from 'react'
import { apiRequest } from '../../services/api'
import ConfirmModal from '../ui/ConfirmModal'
import './NewTaskModal.css'
import './EditTaskModal.css'

export default function EditTaskModal({ task, courses, onClose, onSaved, onDeleted }) {
  const [form, setForm] = useState({ title: task.title || '', description: task.description || '', courseId: task.courseId, dueDate: task.dueDate ? task.dueDate.slice(0, 10) : '', status: task.status, priority: task.priority }); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [confirmation, setConfirmation] = useState(null)
  const update = (event) => setForm({ ...form, [event.target.name]: event.target.value })
  const save = async (event) => { event.preventDefault(); setSaving(true); setError(''); try { const { courseId, ...data } = form; await apiRequest(`/tasks/${task.id}`, { method: 'PATCH', body: JSON.stringify(data) }); onSaved() } catch (requestError) { setError(requestError.message) } finally { setSaving(false) } }
  const archive = () => setConfirmation({ title: 'Guardar tarea', message: 'La tarea pasará a Archivados y podrás restaurarla después.', confirmLabel: 'Archivar', action: async () => { setSaving(true); await apiRequest(`/tasks/${task.id}/archive`, { method: 'PATCH' }); onDeleted() } })
  const remove = () => setConfirmation({ title: 'Eliminar para siempre', message: 'Esta tarea se borrará definitivamente y no podrás recuperarla.', confirmLabel: 'Eliminar definitivamente', danger: true, action: async () => { setSaving(true); await apiRequest(`/tasks/${task.id}`, { method: 'DELETE' }); onDeleted() } })
  const finishConfirmation = async () => { try { await confirmation.action(); setConfirmation(null) } catch (requestError) { setError(requestError.message); setSaving(false); setConfirmation(null) } }
  return <><div className="modal-backdrop" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><form className="task-modal" onSubmit={save}><div className="modal-heading"><div><h2>Editar tarea</h2><p>Título, curso, estado, prioridad y fecha de entrega.</p></div><button type="button" className="modal-close" onClick={onClose}>×</button></div><label>TÍTULO<input name="title" value={form.title} onChange={update} minLength="3" maxLength="200" required /></label><label>DESCRIPCIÓN<textarea name="description" value={form.description} onChange={update} maxLength="2000" /></label><div className="form-grid"><label>CURSO<select name="courseId" value={form.courseId} onChange={update}>{courses.map((course) => <option value={course.id} key={course.id}>{course.name}</option>)}</select></label><label>FECHA DE ENTREGA<input type="date" name="dueDate" value={form.dueDate} onChange={update} /></label><label>ESTADO<select name="status" value={form.status} onChange={update}><option value="PENDING">Pendiente</option><option value="IN_PROGRESS">En proceso</option><option value="COMPLETED">Completada</option></select></label><label>PRIORIDAD<select name="priority" value={form.priority} onChange={update}><option value="LOW">Baja</option><option value="MEDIUM">Media</option><option value="HIGH">Alta</option></select></label></div>{error && <p className="modal-error">{error}</p>}<div className="modal-actions modal-actions-edit"><button type="button" className="archive-button" onClick={archive} disabled={saving}>Archivar</button><button type="button" className="delete-button" onClick={remove} disabled={saving}>Eliminar</button><span /><button type="button" className="cancel-button" onClick={onClose}>Cancelar</button><button type="submit" className="create-button" disabled={saving}>{saving ? 'Guardando...' : 'Guardar cambios'}</button></div></form></div>{confirmation && <ConfirmModal {...confirmation} onClose={() => setConfirmation(null)} onConfirm={finishConfirmation} />}</>
}
