import { useState } from 'react'
import { Archive, CalendarDays, Columns3, LayoutDashboard, BookOpen, LogOut, Menu, X } from 'lucide-react'
import './Sidebar.css'

export default function Sidebar({ active }) {
  const hash = window.location.hash; const current = active || (hash.startsWith('#course/') ? 'courses' : hash.slice(1) || 'dashboard'); const user = JSON.parse(localStorage.getItem('user') || '{}'); const name = user.name || 'Estudiante'; const [open, setOpen] = useState(false)
  const logout = () => localStorage.clear(); const go = () => setOpen(false)
  return <aside className={`sidebar ${open ? 'menu-open' : ''}`}><div className="side-brand"><span className="brand-mark">T</span><strong>TaskBoard</strong><button className="menu-toggle" aria-label={open ? 'Cerrar menú' : 'Abrir menú'} onClick={() => setOpen(!open)}>{open ? <X /> : <Menu />}</button></div><div className="mobile-menu-backdrop" onClick={() => setOpen(false)} /><nav><a onClick={go} className={current === 'dashboard' ? 'active' : ''} href="#dashboard"><span><LayoutDashboard /></span>Dashboard</a><a onClick={go} className={current === 'courses' ? 'active' : ''} href="#courses"><span><BookOpen /></span>Mis cursos</a><a onClick={go} className={current === 'board' ? 'active' : ''} href="#board"><span><Columns3 /></span>Tablero general</a><a onClick={go} className={current === 'calendar' ? 'active' : ''} href="#calendar"><span><CalendarDays /></span>Calendario</a><a onClick={go} className={current === 'archived' ? 'active' : ''} href="#archived"><span><Archive /></span>Archivados</a><a className="mobile-logout" href="#login" onClick={logout}><span><LogOut /></span>Cerrar sesión</a></nav><div className="side-user"><span className="user-avatar">{name.charAt(0).toUpperCase()}</span><div><strong>{name}</strong><small>{user.email || ''}</small></div><a href="#login" onClick={logout}>↪ Cerrar sesión</a></div></aside>
}
